export = {
	REST_API_VERSION: 9 as const,
	GET_CHANNEL_MESSAGES_MAX_RESULTS: 100 as const,
	BULK_DELETE_MESSAGES_MIN: 2 as const,
	BULK_DELETE_MESSAGES_MAX: 100 as const,
	OK_STATUS_CODES: [200, 201, 204, 304]
}
